<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <ProjectReference Include="..\Codions.Contracts\Codions.Contracts.csproj"/>
        <ProjectReference Include="..\Codions.Core\Codions.Core.csproj"/>
        <ProjectReference Include="..\Codions.Infrastructure\Codions.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <_ContentIncludedByDefault Remove="data\workspaces\3c8c613eefc3\context-pack.json"/>
        <_ContentIncludedByDefault Remove="data\workspaces\3c8c613eefc3\job-spec.json"/>
        <_ContentIncludedByDefault Remove="data\workspaces\b6a7a8cb386c\context-pack.json"/>
        <_ContentIncludedByDefault Remove="data\workspaces\b6a7a8cb386c\job-spec.json"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <PropertyGroup>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>fd1cca13-262e-40e2-bde4-ea81b5cc8f4a</UserSecretsId>
    </PropertyGroup>

</Project>
