<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <ProjectReference Include="..\Codions.Contracts\Codions.Contracts.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <PropertyGroup>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>cb5a7e3a-6ec8-45d8-8bdc-65d8f1e6158c</UserSecretsId>
    </PropertyGroup>

</Project>
